name = "GraphOptInterface"
uuid = "2c3d953e-07eb-42f7-9900-e75950e41d88"
authors = ["Jordan Jalving", "Sungho Shin"]
version = "0.1.1"

[deps]
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
Lazy = "50d2b5c4-7a5e-59d5-8109-a42b560f39c0"
MathOptInterface = "b8f27783-ece8-5eb3-8dc8-9495eed66fee"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
DataStructures = "0.18, 0.19"
Lazy="0.15"
Graphs = "1.8"
MathOptInterface = "1.6"
julia = "1.6"
